Repository Unity-Developer-Community/UDC-Bot, pull requests merged in 2021-05, with the labels that each got.

#4 Create BuildAndDeploy.yml
  .github/workflows/DevBranchDeploy.yml
  .github/workflows/ProdBranchDeploy.yml
Labels: enhancement

#5 Working Linkback and improved info handling
  DiscordBot/Modules/UserModule.cs
Labels: enhancement

#1 Publish feed messages in announcement channels
  DiscordBot/Services/FeedService.cs
Labels: enhancement

#2 Better complaints
  DiscordBot/Modules/TicketModule.cs
  DiscordBot/Settings/Deserialized/Settings.cs
  DiscordBot/Settings/Settings.example.json
Labels: enhancement

#3 Reaction role
  DiscordBot/Extensions/ReactionRoles/ReactMessageExtensions.cs
  DiscordBot/Modules/ReactionRoleModule.cs
  DiscordBot/Program.cs
  DiscordBot/Services/CommandHandlingService.cs
  DiscordBot/Services/ReactRoleService.cs
  DiscordBot/Settings/Deserialized/ReactionRole.cs
  DiscordBot/Settings/ReactionRoles.json
Labels: enhancement, help wanted

#6 Fixes getting Asset-Publisher role
  DiscordBot/Modules/UserModule.cs
  DiscordBot/Services/PublisherService.cs
Labels: bug, enhancement
